# Generated by Django 4.2.1 on 2023-06-09 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_trainee_id'),
        ('trainee', '0002_trainee_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
