# Generated by Django 4.2.1 on 2023-05-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainee_id',
        ),
    ]
